# Generated by Django 3.0.1 on 2019-12-31 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0002_auto_20191231_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsdevice',
            name='remote_device_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='beats.RemoteDevice'),
        ),
    ]
