# Generated by Django 3.0.1 on 2020-03-07 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_datetime', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapyTasks',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('create_datetime', models.DateTimeField(auto_now=True)),
                ('finish_datetime', models.DateTimeField(null=True)),
                ('type', models.CharField(choices=[('ITEMS', 'items'), ('INFO', 'info')], max_length=255, null=True)),
                ('status', models.CharField(choices=[('LAUNCH', 'launch'), ('RUNING', 'runing'), ('FINISH', 'finish'), ('ERROR', 'error')], max_length=255, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webscrapy.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, null=True)),
                ('data', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webscrapy.Company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('create_datetime', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('alexa_rank', models.PositiveIntegerField()),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('platform', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.PositiveIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webscrapy.Company')),
            ],
        ),
    ]
