# Generated by Django 3.0.1 on 2020-02-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('create_datetime', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('create_datetime', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('alexa_rank', models.PositiveIntegerField()),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('platform', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.PositiveIntegerField()),
            ],
        ),
    ]
