# Generated by Django 3.0.1 on 2020-02-17 00:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webscrapy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
